import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisProvider from "./components/shared/Lenis";
import Footer from "./components/Footer";
import { lalezar, dmSans } from "./font";
import { SmoothCursor } from "./components/ui/smooth-cursor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lalezar.variable} ${dmSans.variable} font-sans overflow-hidden`}>
        <LenisProvider />
        {/* <SmoothCursor /> */}

        {children}
        <Footer className="mt-20"/>
      </body>
    </html>
  );
}
